name: sin_in

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 8 * * *'
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run
        env:
          host:${{ secrets.host }}
          user:${{ secrets.user }}
          password:${{ secrets.password }}
        run: |
          cd py
          python sign_in.py
